services:
  - type: web
    name: pesaend-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn pesaend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "<your database url>"
